### ISSUE TITLE
Bad svg names

### ISSUE THREAD

**Issue by mmychu** [johanson/ifan03-hass-card#6]
Hi, there is an issue with uncorrect svg names for low and fast profiles:

The card looks like:
![image](https://user-images.githubusercontent.com/25245131/148376361-7e27705d-630a-4069-8a8d-70a3f5dfba16.png)
because 
for fast mode should be fast.svg (no high.svg)
for low mode should be slow.svg (no low.svg)
![image](https://user-images.githubusercontent.com/25245131/148376692-6d1ad310-a59c-4f93-80d0-00b85da30be1.png)

**Comment by johanson** [comment]
Indeed, thank you

https://github.com/johanson/ifan03-hass-card/pull/7
